config/routes.rb
IVFReports::Application.routes.draw do
  resources :scores

  resources :users, :except => :index do 
    resources :requests
  end
  
	resources :sessions, :only => [:new, :create, :destroy]
	
	resources :clinics do
    resources :statistics, :only => [:index]
	  get 'find_clinics_in_state', :on => :collection
	  get 'pull_clinic_data', :on => :collection
	  resources :datapoints
	  resources :requests do 
	    get 'decline', :on => :collection
    end
  end
  
	resources :reviews
	resources :requests, :only => [:test, :create] do
	  get 'test', :on => :collection
  end
  resources :payment_notifications, :only => [:create]
	
	resources :datapoints
	match '/register', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"
  
  match "/find-a-clinic", :to => "pages#clinicfind", :as => :find_a_clinic
  match "/ranking", :to => "pages#ranking"
  match "/our-system", :to => "pages#system", :as => :our_system
  match "/faqs", :to => "pages#faqs"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/terms-and-conditions", :to => "pages#terms", :as => :terms_and_conditions
  match "/privacy-policy", :to => "pages#privacy", :as => :privacy_policy
  match "/clinicians", :to => "pages#clinicians"
  
  match "/reports/the-ivf-process", :to => "reports#the_ivf_process", :as => :the_ivf_process
  match "/reports/infertility-diagnoses", :to => "reports#infertility_diagnoses", :as => :infertility_diagnoses
  match "/reports/cdc-vs-sart", :to => "reports#cdc_vs_sart", :as => :cdc_vs_sart
  match "/reports/fertility-news", :to => "reports#fertility_news", :as => :fertility_news
  match "/reports/other-technologies", :to => "reports#other_technologies", :as => :other_technologies
  match "/reports/clinics-by-region", :to => "reports#clinics_by_region", :as => :clinics_by_region
  match "/reports/clinic-explorer", :to => "reports#clinic_explorer", :as => :clinic_explorer
  match "/reports/clinic-comparator", :to => "reports#clinic_comparator", :as => :clinic_comparator

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :clinic
  default_scope :order => 'ivf_reports_score DESC'
end

app/views/scores/index.html.erb
<%#uninitialized scores controller%>
<h1>Listing scores</h1>

<table>
  <tr>
    <th>Clinic</th>
    <th>Year</th>
    <th>Age group</th>
    <th>Diagnosis</th>
    <th>Cycle type</th>
    <th>Ivf reports score</th>
    <th>Quality score</th>
    <th>Safety score</th>
    <th>Sart score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%= score.clinic_id %></td>
    <td><%= score.year %></td>
    <td><%= score.age_group %></td>
    <td><%= score.diagnosis %></td>
    <td><%= score.cycle_type %></td>
    <td><%= score.ivf_reports_score %></td>
    <td><%= score.quality_score %></td>
    <td><%= score.safety_score %></td>
    <td><%= score.sart_score %></td>
    <td><%= link_to 'Show', score %></td>
    <td><%= link_to 'Edit', edit_score_path(score) %></td>
    <td><%= link_to 'Destroy', score, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Score', new_score_path %>