config/routes.rb
IVFReports::Application.routes.draw do
  resources :scores

  resources :users, :except => :index do 
    resources :requests
  end
  
	resources :sessions, :only => [:new, :create, :destroy]
	
	resources :clinics do
    resources :statistics, :only => [:index]
	  get 'find_clinics_in_state', :on => :collection
	  get 'pull_clinic_data', :on => :collection
	  resources :datapoints
	  resources :requests do 
	    get 'decline', :on => :collection
    end
  end
  
	resources :reviews
	resources :requests, :only => [:test, :create] do
	  get 'test', :on => :collection
  end
  resources :payment_notifications, :only => [:create]
	
	resources :datapoints
	match '/register', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"
  
  match "/find-a-clinic", :to => "pages#clinicfind", :as => :find_a_clinic
  match "/ranking", :to => "pages#ranking"
  match "/our-system", :to => "pages#system", :as => :our_system
  match "/faqs", :to => "pages#faqs"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/terms-and-conditions", :to => "pages#terms", :as => :terms_and_conditions
  match "/privacy-policy", :to => "pages#privacy", :as => :privacy_policy
  match "/clinicians", :to => "pages#clinicians"
  
  match "/reports/the-ivf-process", :to => "reports#the_ivf_process", :as => :the_ivf_process
  match "/reports/infertility-diagnoses", :to => "reports#infertility_diagnoses", :as => :infertility_diagnoses
  match "/reports/cdc-vs-sart", :to => "reports#cdc_vs_sart", :as => :cdc_vs_sart
  match "/reports/fertility-news", :to => "reports#fertility_news", :as => :fertility_news
  match "/reports/other-technologies", :to => "reports#other_technologies", :as => :other_technologies
  match "/reports/clinics-by-region", :to => "reports#clinics_by_region", :as => :clinics_by_region
  match "/reports/clinic-explorer", :to => "reports#clinic_explorer", :as => :clinic_explorer
  match "/reports/clinic-comparator", :to => "reports#clinic_comparator", :as => :clinic_comparator

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :requests
  has_many :clinics

	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation, :gender, :zip_code, :ethnicity, :birthday, :previous_cycles, :infertility_diagnosis, :abo_blood_type, :rh_factor, :height_ft, :height_inches, :weight, :day_3_fsh, :day_3_e2, :day_3_lh, :day_10_fsh, :day_10_e2, :day_10_lh, :prolactin, :uterine_fibroids, :uterine_tumors, :phone, :about_me, :zip_distance
	
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	username_regex = /^[A-Za-z\d_]+$/
	
	validates :name,	:presence => true,
						        :length => { :maximum => 50 },
						        :format => { :with => username_regex },
						        :uniqueness => { :case_sensitive => false }
						
	validates :email,	:presence => true, 
						        :format => { :with => email_regex }, 
						        :uniqueness => { :case_sensitive => false }
						
	validates :password, 	:presence => true,
							          :confirmation => true,
							          :length => {:within => 6..40},
							          :on => :create
							          
	validates :password,  :confirmation => true,
	                      :on => :update
	
	
	before_save :encrypt_password, :unless => "password.blank?" || "confirmation.blank?"
  
	before_save :create_permalink
	
	def to_param
		permalink
	end
	
	
	#Return true if the user's password matches the submitted password.
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)#compare encrypted_password with the version in db
	end
	
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end
	
	
	private
	
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end
		
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
		
		def create_permalink
			self.permalink = name.downcase
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :correct_user, 	:only => [:edit, :update]
  before_filter :admin_user, 	:only => :destroy
  
  def index
	  @title = "All Users"
	  @users = User.paginate(:page => params[:page])
  end
  
  def show
	  @user = User.find_by_permalink(params[:id])
	  
	  if @user.clinician?
	    redirect_to @user.clinics.first unless current_user?(@user)
    end
    
	  @title = @user.name
    
	  age_group = "All Ages"
	  diagnosis = "All Diagnoses"
	  cycle_type = "fresh"
	  year = "2010"

	  if(@user.birthday.nil?)
	    user_age = 0
    else
      user_age = ((Date.today) - (@user.birthday)).to_i/365
    end
    
    if(@user.infertility_diagnosis.nil?)
      diagnosis = "All Diagnoses"
	  elsif(@user.infertility_diagnosis=="endometriosis")
	    diagnosis = "Endometriosis"
	  elsif(@user.infertility_diagnosis=="diminished_ovarian_reserve")
	    diagnosis = "Diminished Ovarian Reserve"
	  elsif(@user.infertility_diagnosis=="multiple_female_factors")
	    diagnosis = "Multiple Female Factors"
	  elsif(@user.infertility_diagnosis=="ovulatory_dysfunction")
	    diagnosis = "Ovulatory Dysfunction"
	  elsif(@user.infertility_diagnosis=="tubal_factor")
	    diagnosis = "Tubal Factor"
	  elsif(@user.infertility_diagnosis=="female_and_male_factors")
	    diagnosis = "Female and Male Factors"
	  elsif(@user.infertility_diagnosis=="male_factor")
	    diagnosis = "Male Factor"
	  elsif(@user.infertility_diagnosis=="other_factor")
	    diagnosis = "Other Factor"
	  elsif(@user.infertility_diagnosis=="uterine_factor")
	    diagnosis = "Uterine Factor"
	  elsif(@user.infertility_diagnosis=="unknown_factor")
	    diagnosis = "Unknown Factor"
	  else
	    diagnosis = "All Diagnoses"
    end
	  
	  if(user_age < 35)
	    age_group = "<35"
    elsif(user_age >= 35 && user_age <= 37)
      age_group = "35-37"
    elsif(user_age >= 38 && user_age <= 40)
      age_group = "38-40"
    elsif(user_age >= 41 && user_age <= 42)
      age_group = "41-42"
    else
	    age_group = ">42"
	  end
	  
	  unless @user.zip_code.nil?
	    @coordinates = Geocoder.search(@user.zip_code)
    end
    
    if @coordinates.nil? || @coordinates.empty?
      @scores = Score.where(:year => year, :cycle_type => cycle_type, :diagnosis => diagnosis, :age_group => age_group).limit(5).offset(0)

  	  if(@scores.empty?)
  	    diagnosis = "All Diagnoses"
  	    @scores = Score.where(:year => year, :cycle_type => cycle_type, :diagnosis => diagnosis, :age_group => age_group).limit(5).offset(0)
      end
    else #If there is a zip code for the user and coordinates are produced
      lat_offset = 1.5
      long_offset = 1.5
      
      if @user.zip_distance=='25'
        lat_offset = 0.75
        long_offset = 0.75
      elsif @user.zip_distance=='50'
        lat_offset = 1.5
        long_offset = 1.5
      elsif @user.zip_distance=='100'
        lat_offset = 3.0
        long_offset = 3.0
      elsif @user.zip_distance=='200'
        lat_offset = 6.0
        long_offset = 6.0
      elsif @user.zip_distance=='ALL'
        lat_offset = 180.0
        long_offset = 180.0
      end
      
    	lat = @coordinates[0].latitude
    	low_lat = lat - lat_offset
    	high_lat = lat + lat_offset
    	long = @coordinates[0].longitude
    	low_long = long - long_offset
    	high_long = long + long_offset
      @scores = Score.where(:year => year, :cycle_type => cycle_type, :diagnosis => diagnosis, :age_group => age_group).joins(:clinic).where(:clinics => {:latitude => low_lat..high_lat, :longitude => low_long..high_long}).limit(5).offset(0)

  	  if(@scores.empty?)
  	    diagnosis = "All Diagnoses"
  	    @scores = Score.where(:year => year, :cycle_type => cycle_type, :diagnosis => diagnosis, :age_group => age_group).joins(:clinic).where(:clinics => {:latitude => low_lat..high_lat, :longitude => low_long..high_long}).limit(5).offset(0)
      end
  	end
	  

    
	  @clinic_results = Array.new;
    unless @scores.empty?
      @scores.each do |s|
        if(s.clinic_id==384)
          
        else
          cur_clinic = Clinic.find_by_id(s.clinic_id)
          cur_new_object = cur_new_object = {'ivf_reports_score' => s.ivf_reports_score, 'quality_score' => s.quality_score, 'safety_score' => s.safety_score, 'sart_score' => s.sart_score, 'clinic_id' => cur_clinic.id, 'clinic_name' => cur_clinic.clinic_name, 'permalink' => cur_clinic.permalink, 'city' => cur_clinic.city, 'state' => cur_clinic.state, 'address' => cur_clinic.address, 'practice_director' => cur_clinic.practice_director, 'lab_director' => cur_clinic.laboratory_director, 'medical_director' => cur_clinic.medical_director, 'zip' => cur_clinic.zip}
          @clinic_results << cur_new_object
        end
      end
    end
  end

  def new
	  @title = "Sign Up"
	  @user = User.new
  end

  def create
	  @user = User.new(params[:user])
	  if @user.save
	    sign_in @user
	    flash[:success] = "Welcome to IVF Reports!"
	    

      email_body = "<img src='#{root_url}#{ActionController::Base.helpers.asset_path('logo.png')}'><br/>"
	    email_body += "<h1>Welcome to IVF Reports</h1>"
	    email_body += "<p>IVF Reports is the premier website for finding accurate information about U.S. Fertility Clinics. Our data specialists will help you find the best clinic <i>for you</i>.</p>"
	    email_body += "<p>Your Account Information:</p>"
	    email_body += "<ul><li><b>Username: </b>#{@user.name}</li>"
	    email_body += "<li><li><b>Email: </b> #{@user.email}</li></ul>"
	    email_body += "<p>#{ActionController::Base.helpers.link_to('Log in', signin_path)} to view personal recommendations for clinics best suited to treat you. You may contact up to five clinics through our system. Our relationships with Fertility Clinics will allow your case to receive high-level attention from a physician who can help you get pregnant.</p>"
      email_body += "<p>Thank you for being a part of our community. We look forward to helping you embark on your fertility journey.</p>"
      email_body += "<p>Warmest regards,</p>"
      email_body += "<p>The IVF Reports Team</p>"


      Pony.mail( 
      	:to => @user.email,
      	:subject => 'Welcome to IVF Reports.',
        :headers => { 'Content-Type' => 'text/html' },      	
      	:body => email_body
      )
	    
	    redirect_to @user
	  else
	    @title = "Sign Up"
	    render 'new'
	  end
  end

  def edit
	  @title = "Settings"
  end
  
  def update
	  @user = User.find_by_permalink(params[:id])
	  
    success = false
    
    unless params[:personal_info].nil?
      if @user.update_attributes(params[:personal_info])
        success = true
	    end
    end
	  
	  unless params[:medical_info].nil?
	    if @user.update_attributes(params[:medical_info])
        success = true
	    end
	  end

	  unless params[:account_info].nil?	  
	    if @user.update_attributes(params[:account_info])
        success = true
	    end
    end
	  
	  @response = @user.errors
	  
	  respond_to do |format|
	    format.html do |f| 
	        if @user.update_attributes(params[:user])
            flash[:success] = "Zip Code Radius Successfully Updated"
    	      redirect_to @user
  	      else
  	        flash[:error] = "There was an error processing your request."
  	        render 'show'
    	    end
      end
	    format.js {render :layout => false }
    end
  end
  
  def destroy
	  if current_user?(User.find_by_permalink(params[:id]))
		  flash[:notice] = "You cannot destroy yourself"
	  else
		  User.find_by_permalink(params[:id]).destroy
		  flash[:success] = "User destroyed."
	  end
	  respond_to do |format|
	    format.html
	    format.js
    end
  end
  
  private
	
	def correct_user
	  @user = User.find_by_permalink(params[:id])
	  redirect_to(root_path) unless current_user?(@user)
	end
	
	def admin_user
	  redirect_to(root_path) unless current_user.admin?
	end
	
	def insurance_user
	  redirect_to(root_path) unless current_user.insurer?
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase,	:alt => user.name,
												:class => 'gravatar',
												:gravatar => options)
	end
	
	def large_gravatar_for(user, options = {:size => 150})
	  gravatar_image_tag(user.email.downcase,	:alt => user.name,
	                      :style => 'display:block;margin-left:auto;margin-right:auto;',
												:class => 'large_gravatar',
												:gravatar => options)
	end
	
	def contacts_remaining(user)
	  outstanding_contacts = user.requests.where(:declined => false)
	  remaining = (5 - outstanding_contacts.count)
  end
end

app/views/users/new.html.erb
<h1>Register</h1>
<p>Register for an IVF Reports account to receive FREE access to some of our premium features including:</p>
<ul class="content_list">
	<li>Clinic Review Access</li>
	<li>Favorite Clinics List</li>
	<li>Personalized Clinic Recommendations</li>
	<li>Contact a Clinic</li>
	<li>Cycle Tracking System</li>
	<li>A Community of Engaged Patients Like You</li>
</ul>
<div class="register_form">
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
		<h2 class="register_blurb">Become a Member of the IVF Reports Community</h2>
		<h3>Required Fields</h3>
	<table class="register_form">
	<tr>
		<td class="label"><%= f.label :name, 'Username' %></td>
		<td><%= f.text_field :name %></td>
	</tr>
	<tr>
		<td class="label"><%= f.label :email %></td>
		<td><%= f.text_field :email %></td>
	</tr>
	<tr>
		<td class="label"><%= f.label :password %></td>
		<td><%= f.password_field :password %></strong></td>
	</tr>
	<tr>
		<td class="label"><%= f.label :password_confirmation, "Confirmation" %></td>
		<td><%= f.password_field :password_confirmation %></td>
	</tr>
	</table>
	<h3>Optional Fields - Get More Accurate Recommendations!</h3>
	<table class="register_form">
		<tr>
			<td class="label"><%= f.label :gender %></td>
				<% gender_select = options_for_select([['-'],['Male','male'],['Female','female']])%>
			<td class="input"><%= f.select(:gender, gender_select) %></td>
		</tr>
		<tr>
			<td class="label"><%= f.label :birthday %></td>
			<td class="input"><%= f.date_select :birthday, {
				:start_year => Time.now.year,
			  	:end_year => 1900,
			  	:use_short_month => true,
			  	:order => [:month, :day, :year],
			  	:prompt => {:month => 'Month', :day => 'Day', :year => 'Year'}} %></td>
		</tr>
		<tr>
			<td class="label"><%= f.label :zip_code %></td>
			<td class="input"><%= f.text_field :zip_code, :size=>"5"  %></td>
		</tr>
		<tr>	
			<td class="label"><%= f.label :ethnicity %></td>
			<% ethnicity_select = options_for_select([['-'],['Caucasian','caucasian'],['East Asian','east_asian'],['South Asian','south_asian'],['Arabic','arabic'],['African','african'],['Hispanic','hispanic'],['Native American','native_american'],['Other','other']])%>
			<td class="input"><%= f.select(:ethnicity, ethnicity_select) %></td>
		</tr>
		<tr>
			<td class="label"><%= f.label :previous_cycles, "Previous Cycles" %></td>
			<% cycles_select = options_for_select([['-'],['0',0],['1',1],['2',2],['3',3],['4',4],['5',5],['6',6]]) %>
			<td class="input"><%= f.select(:previous_cycles, cycles_select) %></td>
		</tr>
		<tr>
			<td class="label"><%= f.label :infertility_diagnosis, "Infertility Diagnosis" %></td>
				<% diagnosis_options = options_for_select([['-'],['Endometriosis','endometriosis'],['Diminished Ovarian Reserve','diminished_ovarian_reserve'],['Multiple Female Factors','multiple_female_factors'],['Ovulatory Dysfunction','ovulatory_dysfunction'],['Tubal Factor','tubal_factor'],['Female and Male Factors','female_and_male_factors'],['Male Factor','male_factor'],['Other Factor','other_factor'],['Uterine Factor','uterine_factor'],['Unknown Factor','unknown_factor']]) %>
			<td class="input"><%= f.select(:infertility_diagnosis, diagnosis_options) %></td>
		</tr>
	</table>
		<div class="update_button"><%= f.submit "Register" %></div>

		<span class="terms_agreement"><i>*By registering, you acknowledge that you agree to our <%= link_to "Terms and Conditions", terms_and_conditions_path %> and have reviewed our <%= link_to "Privacy Policy", privacy_policy_path %>.</i></span>

<% end %>
</div>

app/views/users/show.html.erb
<div class='user_profile'>

<div class="profile_top">
	<div class="gravatar-and-name">
		<%= gravatar_for @user %>
		<div class="user_info">
			<h1><%= @user.name %></h1>
			<span class="user_subtitle">Joined <%= @user.created_at.strftime("%B %d, %Y") %></span>
		</div>
	</div>

	<div class="edit-profile-link">
	<% if current_user?(@user) %>
		<% unless current_user.clinician? %>
		<%= link_to edit_user_path(current_user), :class => "edit-button" do %><span class="icon">⚙</span>Edit Your Profile<% end %>
		<% end %>
	<% end %>
	</div>
</div>

<% if current_user?(@user) && current_user.clinician? # This is what users will see when they are clinicians viewing their own user profile. %>
<ul class="clinic_account_options">
		<li><%= link_to clinic_path(current_user.clinics.first) do |l| %><span class="clinic_rec_rank round" ><span class="icon">⌂</span></span>View My Clinic<% end %></li>
		<li><%= link_to edit_clinic_path(current_user.clinics.first) do |l| %><span class="clinic_rec_rank round" ><span class="icon">⚙</span></span>Edit My Clinic<% end %></li>
		<li><%= link_to clinic_requests_path(Clinic.find_by_user_id(current_user.id)) do |l| %><span class="clinic_rec_rank round"><span class="icon">u</span></span>View My Clinic's Leads<% end %></li>
		<li><%= link_to edit_user_path(current_user) do |l| %><span class="clinic_rec_rank round"><span class="icon">⚙</span></span>Edit My Account<% end %></li>
		<li><%= link_to [Clinic.find_by_user_id(current_user.id), :statistics] do |l| %><span class="clinic_rec_rank round"><span class="icon">C</span></span>View In Depth Reporting<% end %></li>		
</ul>
<% else %>
	<% if @user.clinician? %>
		<% #This is what users will see when visiting a clinician's user page (rare event) who are not that user themselves. %>
	<% else #What normal users see (about themselves and other users?) need to make sure no contact information exists when viewed by others. %>
		<div class="personal_info user_info_section">
		<h2>Personal Information</h2>
		<hr>
		<table class="personal_info">
			<tr><td>Name</td><td><%= @user.name %></td></tr>
			<% if current_user?(@user) %><tr><td>Email</td><td><%= link_to @user.email, @user.email %></td></tr><% end %>
			<tr><td>Gender</td><td><%= @user.gender.capitalize unless @user.gender.nil? %></td></tr>
			<tr><td>Ethnicity</td><td><%= @user.ethnicity.capitalize unless @user.ethnicity.nil? %></td></tr>
			<tr><td>Age</td><td><% if @user.birthday.nil? %><% else %><%= (Date.today - @user.birthday).to_i/365 %> Years Old <% end %></td></tr>
			<tr><td>Zip Code</td><td><% if @user.zip_code.nil? %>-<% else %><%= @user.zip_code %><% end %></td></tr>
			<tr><td>IVF Attempts</td><td><%= @user.previous_cycles unless @user.previous_cycles.nil? %></td></tr>
			<tr><td>Infertility Diagnosis</td><td><%= @user.infertility_diagnosis.gsub("_"," ").capitalize unless @user.infertility_diagnosis.nil? %></td></tr>
			<tr><td>Member Since</td><td><%= @user.created_at.strftime("%B %d, %Y") %></td></tr>
			<% if current_user?(@user) %><tr><td>About You</td><td class="about_me"><%= @user.about_me %></td></tr><% end %>
		</table>
		</div>

		<% if current_user?(@user) %>
		<div class="personal_info user_info_section">
			<h2>Personalized Clinic Recommendations</h2>
			<hr>
			<% unless @user.zip_code.nil? || @user.zip_code.empty? %>
				<span class="recommendation_distance">Currently showing clinics within <%= @user.zip_distance %> miles of <%= @user.zip_code %>.</span>
				<%= form_for @user do |f| %>
				<table class="personal_info zip_search">
					<% zip_distance_options = options_for_select([['-'],['25','25'],['50','50'],['100','100'],['200','200'], ['All Distances','ALL']], @user.zip_distance) %>
					<tr><td><%= f.label :zip_distance, 'Miles to Search Within' %></td><td><%= f.select(:zip_distance, zip_distance_options) %></td><td><%= f.submit :value => "Update" %></td></tr>
				</table>
				<% end %>
			<% end %>
			<ul class="personal_rec_table">
				<% 
				count = 0
				@clinic_results.each do |c| %>
					<% count += 1 %>
					<li><a class="rank_link" href="../clinics/<%= c['permalink'] %>"><span class="clinic_rec_rank round" ><%= count %></span></a><span class="clinic_name"><a href="../clinics/<%= c['permalink'] %>" target="_blank"><%= c['clinic_name'] %></a></span><span class="clinic_location"><%= c['city'] %>, <%= c['state'] %></span></li>
				<% end %>
			</ul>
		</div>

		<div class="personal_info user_info_section">
			<h2>Clinics Contacted (<%= contacts_remaining(@user) %> Requests Remaining)</h2>
			<div id="contacted_accordion">
				<% if @user.requests.empty? %>
					<h3><a href="#">None Contacted Yet.</a></h3>
				<% else %>
					<% @user.requests.each do |r| %>
					<h3><a href="#"><%= r.clinic.clinic_name %> - <%= r.clinic.city %>, <%= r.clinic.state %></a></h3>
					<div>
						<table class="contacted_table">
						<tr><td class="label">Clinic</td><td class="value"><%= link_to r.clinic do |l| %><span class="icon">⌂</span><%= r.clinic.clinic_name %><% end %></td></tr>
						<tr><td class="label">Contacted</td><td class="value"><%= r.created_at.strftime("%B %d, %Y") %></td></tr>
						<tr>
							<td class="label">Response</td>
							<td class="value">
								<% if r.visible==true %>
									<%= "Contact Accepted - #{r.updated_at.strftime("%B %d, %Y")}" %>
								<% elsif r.declined==true %>
									<%= "Contact Declined - #{r.updated_at.strftime("%B %d, %Y")}" %>
								<% else %>
									<%= "No Response Yet" %>
								<% end %>
							</td>
						</tr>
						</table>
					</div>
					<% end %>
				<% end %>
			</div>
		</div>
		<% end %>


	<% end %>
<% end %>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('#contacted_accordion').accordion();
});
</script>

app/views/users/update.js.erb
<% if(@response.count==0) %>
	$('div.update_results').html('Profile Successfully Updated.');
	$('div.update_results').addClass('success');
	$('div.update_results').removeClass('hidden');
	setTimeout("$('div.update_results').addClass('hidden');",2000);
	setTimeout("$('div.update_results').removeClass('success');",2000);	
<% else %>
	var html = "";
	<% @response.each do |attr, msg| %>
		html = html + '<%= attr.capitalize %>';
		html = html + " <%= msg %>.<br/>";
	<% end %>
	$('div.update_results').html(html);
	$('div.update_results').addClass('error');
	$('div.update_results').removeClass('hidden');
	setTimeout("$('div.update_results').addClass('hidden');",2000);
	setTimeout("$('div.update_results').removeClass('error');",2000);		
<% end %>