config/routes.rb
IVFReports::Application.routes.draw do
  resources :scores

  resources :users, :except => :index do 
    resources :requests
  end
  
	resources :sessions, :only => [:new, :create, :destroy]
	
	resources :clinics do
    resources :statistics, :only => [:index]
	  get 'find_clinics_in_state', :on => :collection
	  get 'pull_clinic_data', :on => :collection
	  resources :datapoints
	  resources :requests do 
	    get 'decline', :on => :collection
    end
  end
  
	resources :reviews
	resources :requests, :only => [:test, :create] do
	  get 'test', :on => :collection
  end
  resources :payment_notifications, :only => [:create]
	
	resources :datapoints
	match '/register', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"
  
  match "/find-a-clinic", :to => "pages#clinicfind", :as => :find_a_clinic
  match "/ranking", :to => "pages#ranking"
  match "/our-system", :to => "pages#system", :as => :our_system
  match "/faqs", :to => "pages#faqs"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/terms-and-conditions", :to => "pages#terms", :as => :terms_and_conditions
  match "/privacy-policy", :to => "pages#privacy", :as => :privacy_policy
  match "/clinicians", :to => "pages#clinicians"
  
  match "/reports/the-ivf-process", :to => "reports#the_ivf_process", :as => :the_ivf_process
  match "/reports/infertility-diagnoses", :to => "reports#infertility_diagnoses", :as => :infertility_diagnoses
  match "/reports/cdc-vs-sart", :to => "reports#cdc_vs_sart", :as => :cdc_vs_sart
  match "/reports/fertility-news", :to => "reports#fertility_news", :as => :fertility_news
  match "/reports/other-technologies", :to => "reports#other_technologies", :as => :other_technologies
  match "/reports/clinics-by-region", :to => "reports#clinics_by_region", :as => :clinics_by_region
  match "/reports/clinic-explorer", :to => "reports#clinic_explorer", :as => :clinic_explorer
  match "/reports/clinic-comparator", :to => "reports#clinic_comparator", :as => :clinic_comparator

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :clinic
  belongs_to :user
  
  default_scope :order => 'created_at DESC'
  
  
  #can add a method that calculates the price
  
  def paypal_encrypted(return_url, notify_url)
    user = User.find_by_id(user_id)
    
    values = {
      :business => "info@ivfreports.org",
      :lc => 'US',
      :cmd => '_xclick',
      :item_name => "Patient Lead: #{user.name}",
      :item_number => id,
      :invoice => id,
      :amount => 100.00,
      :currency_code => 'USD',
      :notify_url => notify_url,
      :rm => 1,
      :return => return_url,
      :cert_id => '6RRSVX4ACHKP2'
    }
    
    "https://www.paypal.com/cgi-bin/webscr?" + values.to_query
    
  end
  
  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate, :only => [:index, :show, :purchase, :create]
  before_filter :correct_user, :only => [:index, :show, :purchase]
  before_filter :clinic_or_admin_user, :only => :show
  
  def index #Clinics can see all requests made to them and opt to purchase them here. Admins can see all requests.
    if params[:clinic_id].nil? && params[:user_id].nil? && current_user.admin? #Only the admins can see the full request index
      @title = "All Leads"
      @requests = Request.all
    elsif !params[:clinic_id].nil?
      @clinic = Clinic.find(params[:clinic_id])
      @requests = @clinic.requests.where(:declined => false)
      @title = "Leads for #{@clinic.clinic_name}"
    elsif !params[:user_id].nil?
      @user = User.find_by_permalink(params[:user_id])
      @requests = @user.requests
      @title = "Clinics You Have Contacted"
    end
  end
  
  def show #This will provide a more in depth summary about the use/patient who has made the contact request.
    if params[:clinic_id].nil? && current_user.admin?
      @request = Request.find(params[:id])
      @request_user = User.find(@request.user_id)
    else
      @clinic = Clinic.find(params[:clinic_id])
      @request = Request.find(params[:id])
      @request_user = User.find(@request.user_id)
    end
    
    respond_to do |format|
      format.html {}
    end
  end
  
  def test
    @request = Request.where(:clinic_id => params[:clinic_id], :user_id => params[:user_id])
    
    respond_to do |format|
      format.json {render :json => @request.to_json()}
    end    
  end
  
  def decline #This will be the method for declining a request
    @request = Request.where(:user_id => params[:user_id], :clinic_id => params[:clinic_id]).first
    @clinic = Clinic.find_by_id(params[:clinic_id])
    if @request.toggle!(:declined)
      if @request.declined==true
        flash[:success] = "Request from #{@request.user.name} Declined."
      else
        flash[:success] = "Error Declining Request."
      end
    else
      flash[:error] = "Request Unchanged."
    end
    redirect_to clinic_requests_path(@clinic)
  end
  
  def create
    if(params[:request].nil?)
      params[:request] = {:user_id => params[:user_id], :clinic_id => params[:clinic_id]}
    end
    
    if params[:user_id].nil?
      @user = User.find_by_id(params[:request][:user_id])      
    else
      @user = User.find_by_id(params[:user_id])
    end
    
    request_count = @user.requests.where(:declined => false).count
    
    if request_count>=5
      @response = "5"
    else
      @clinic = Clinic.find(params[:request][:clinic_id])
      if Request.where(:clinic_id => params[:request][:clinic_id], :user_id => params[:request][:user_id]).empty?
        @request = Request.new(params[:request])
        @request.save
	      @response = "#{request_count}"
      end
    end
    respond_to do |format|
      format.js {render :response => @response}
      format.json {render :json => @response.to_json() }
    end
  end
  
  private
    def correct_user #It has to be the patient, the clinic the patient belongs to, or an admin
      if current_user.admin?
      elsif current_user.clinician?
        @clinic = Clinic.find(params[:clinic_id])
        if @clinic.user_id.nil? #The clinic has not been claimed
          redirect_to(@clinic)
        else
          @clinic_user = User.find(@clinic.user_id)
  	      redirect_to(@clinic) unless current_user?(@clinic_user)
	      end
	    else
	      @current_user = User.find_by_permalink(params[:user_id])
	      redirect_to(@current_user) unless current_user?(@current_user)
	    end
  	end
  	
  	def clinic_or_admin_user
      unless current_user.admin? || current_user.clinician?
        @user = User.find_by_permalink(params[:user_id])
      end
  	  redirect_to([@user, :requests]) unless current_user.admin? || current_user.clinician?
	  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/create.js.erb
var server_response = <%= @response %>;
if(parseInt(server_response)===5){
	alert("You have already contacted 5 clinics.");
}
else{
	$('li.request_button').html("<a href='#'><span class='request_button_old'>Contact Request Sent</span></a>");	
	if(parseInt(server_response)===3){
		alert("You have " + (4 - parseInt(server_response)) + " clinic left to contact.");
	}
	else{
		alert("You have " + (4-parseInt(server_response)) + " clinics left to contact.");
	}
}

app/views/requests/index.html.haml
- if !params[:clinic_id].nil? #If the user is a clinician..or Admin in a clinic's nested request resource
 %h1 Viewing Leads for #{@clinic.clinic_name}
- elsif !params[:user_id].nil? #IF the user is a user..  
 %h1 Viewing Clinics You Have Contacted
- elsif current_user.admin? #If the user is an admin a.k.a. all leads view
 %h1 Viewing All Leads

%ul.request_list
 %li.header.round
  %span.username Username
  %span.age Age
  %span.created Contact Requested
  %span.view_button View
 - @requests.each do |r|
  - user_info = User.find_by_id(r.user_id)
  - if r.visible? #Show full information if they have paid for the lead.
   %li
    %span.username
     = "#{user_info.name} (Paid)"
    %span
     - if user_info.birthday.nil?
      = '-'
     - else
      = (Date.today - user_info.birthday).to_i/365
    %span.created
     = r.created_at.strftime("%B %d, %Y")
    = link_to clinic_request_path(@clinic, r) do |l| 
     %span.view_button.icon
      E 
  - else #Show limited..teaser info if the lead is not paid for
   %li
    %span.username
     = user_info.name
    %span.age
     - if user_info.birthday.nil?
      = '-'
     - else 
      = (Date.today - user_info.birthday).to_i/365
    %span.created
     = r.created_at.strftime("%B %d, %Y")
    = link_to clinic_request_path(@clinic, r) do |l|
     %span.view_button.icon   
      E
     
         

app/views/requests/show.html.haml
%h1 Contact Request: #{@request.created_at.strftime("%B %d, %Y") }
.personal_info.user_info_section
 %h2 Patient Information
 %hr
 %table.personal_info
  %tr
   %td Username
   %td
    = link_to @request_user.name, @request_user 
  - if @request.visible?
   %tr
    %td Email
    %td 
     = link_to @request_user.email, @request_user.email
  %tr
   %td Gender
   %td
    =  @request_user.gender.capitalize unless @request_user.gender.nil?
  %tr
   %td Ethnicity
   %td
    = @request_user.ethnicity.capitalize unless @request_user.ethnicity.nil?  
  %tr
   %td Age
   %td
    - if @request_user.birthday.nil? 
    - else
     #{(Date.today - @request_user.birthday).to_i/365} Years Old   
  %tr
   %td Previous IVF Attempts
   %td
    = @request_user.previous_cycles unless @request_user.previous_cycles.nil?
  %tr
   %td Infertility Diagnosis
   %td
    = @request_user.infertility_diagnosis.gsub("_"," ").capitalize unless @request_user.infertility_diagnosis.nil?
  %tr 
   %td IVF Reports Member Since
   %td 
    = @request_user.created_at.strftime("%B %d, %Y")          

.personal_info.user_info_section
 %h2 Contact This Patient
 %hr
 - if @request.visible? || current_user.admin?
  %table.personal_info
   %tr
    %td Email
    %td
     = @request_user.email
   %tr
    %td Phone
    %td
     - if @request_user.phone.nil?
      %i Phone Number Not Provided
     - else
      = @request_user.phone
 - else #This needs to be a button whereby a clinic can purchase access to the patient's contact information (we also need the purchase to trigger an email with the contact info)

  .purchase_request
   %span.purchase_button.round
    = link_to 'Purchase Contact Information', @request.paypal_encrypted(clinic_request_url(@clinic, @request), payment_notifications_url)

  .deny_request
   %span.deny_button.round
    = link_to 'Decline Info', decline_clinic_requests_path(@clinic,:user_id => @request.user_id, :clinic_id => @request.clinic_id), :confirm => "Are You Sure You Want to Decline this Request?"
   