config/routes.rb
IVFReports::Application.routes.draw do
  resources :scores

  resources :users, :except => :index do 
    resources :requests
  end
  
	resources :sessions, :only => [:new, :create, :destroy]
	
	resources :clinics do
    resources :statistics, :only => [:index]
	  get 'find_clinics_in_state', :on => :collection
	  get 'pull_clinic_data', :on => :collection
	  resources :datapoints
	  resources :requests do 
	    get 'decline', :on => :collection
    end
  end
  
	resources :reviews
	resources :requests, :only => [:test, :create] do
	  get 'test', :on => :collection
  end
  resources :payment_notifications, :only => [:create]
	
	resources :datapoints
	match '/register', :to => 'users#new'
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  root :to => "pages#home"
  
  match "/find-a-clinic", :to => "pages#clinicfind", :as => :find_a_clinic
  match "/ranking", :to => "pages#ranking"
  match "/our-system", :to => "pages#system", :as => :our_system
  match "/faqs", :to => "pages#faqs"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/terms-and-conditions", :to => "pages#terms", :as => :terms_and_conditions
  match "/privacy-policy", :to => "pages#privacy", :as => :privacy_policy
  match "/clinicians", :to => "pages#clinicians"
  
  match "/reports/the-ivf-process", :to => "reports#the_ivf_process", :as => :the_ivf_process
  match "/reports/infertility-diagnoses", :to => "reports#infertility_diagnoses", :as => :infertility_diagnoses
  match "/reports/cdc-vs-sart", :to => "reports#cdc_vs_sart", :as => :cdc_vs_sart
  match "/reports/fertility-news", :to => "reports#fertility_news", :as => :fertility_news
  match "/reports/other-technologies", :to => "reports#other_technologies", :as => :other_technologies
  match "/reports/clinics-by-region", :to => "reports#clinics_by_region", :as => :clinics_by_region
  match "/reports/clinic-explorer", :to => "reports#clinic_explorer", :as => :clinic_explorer
  match "/reports/clinic-comparator", :to => "reports#clinic_comparator", :as => :clinic_comparator

end

app/views/layouts/_call_to_action.html.haml
.call_to_action_page
 %h1 Welcome to IVF Reports
 .call_to_action.round
  %h2.top-round For Patients
  %ul
   %li Personalized Clinic Recommendations.
   %li Maximize Your Chance at Pregnancy
   %li
    %span Utilize Our
    %i Clinic Contact System
   %li Meet Couples with Shared Experiences
  %span.register_now.round
   = link_to "Register Now", register_path, :class => 'round'
 .call_to_action.round
  %h2.top-round For Clinicians
  %ul
   %li Manage your Clinic's Profile
   %li Meet New Patients
   %li Become More Visible Online
   %li Advanced Statistics and Reporting           
  %span.register_now.round
   = link_to "Register Now", clinicians_path, :class => 'round'
       

app/views/layouts/_footer.html.haml
%footer
 .container_12
  .grid_12.footer_border
   %nav.footer_nav
    %ul
     %li 
      = link_to "About Us", about_path
     %li 
      = link_to "Terms and Conditions", {:controller => 'pages', :action => 'terms' }
     %li 
      = link_to "Privacy Policy", {:controller => 'pages', :action => 'privacy'}
     %li 
      = link_to "Clinicians", clinicians_path
     %li 
      = link_to "Contact", contact_path
   .footer_text 
    %span IVF Reports. An
    %a{ :href => "#", :target => "_blank" } Althea
    %span creation.
 

app/views/layouts/_header.html.haml
%header
 .container_12
  .grid_12
   .grid_12.alpha.omega
    %h1.hidden IVF Reports
    .header_top
     %span.logo
      = link_to root_path do
       %span
     %span.authentication
      %ul
       - if signed_in?
        %li
         = link_to signout_path do
          %span.icon ⊝
          %span Sign Out
        %li
         = link_to edit_user_path(current_user), :class => is_active?('users#edit') do
          %span.icon ⚙
          %span Settings
        %li
         = link_to user_path(current_user), :class => is_active?('users#show') do
          %span.icon u
          %span 
           = current_user.name
        - if current_user.clinician?
         %li
          = link_to clinic_path(current_user.clinics.first) do
           %span.icon ⌂
           %span My Clinic
       - else
        %li
         = link_to "Register", register_path, :class => is_active?('users#new') 
        %li.divider 
         = "|"
        %li
         = link_to "Sign In", signin_path, :class => is_active?("sessions#new")   


   .grid_12.alpha.omega
    .header_nav
     %nav.header    
      %ul
       %li{ :class => "#{is_active?("pages#home")}"}  
        = link_to "Home", root_path
       %li{ :class => "#{is_active?("pages#clinic_find")}"}            	                 
        = link_to "Find a Clinic", { :controller => 'pages', :action => 'clinicfind'  } 
       %li{ :class => "#{is_active?("pages#ranking")}"} 
        = link_to "Ranking", ranking_path
       %li{ :class => "#{is_active?("pages#system")}"}
        = link_to "Our System", { :controller => 'pages', :action => 'system' }
       %li{ :class => "#{is_active?("pages#faqs")}"}
        = link_to "Faqs", faqs_path
       %li.search
        %span.icon z
        %input{ :type => 'text' }


   - if is_controller?('pages') and is_action?('home')
    .grid_12.alpha.omega
     .header_pic

app/views/layouts/_left_sidebar.html.haml
.left_sidebar
 %ul.sidebar_module
  %li.header Reports
  - if signed_in?
   %li 
    = link_to user_path(current_user), :class => is_active?('users#show') do
     %span.icon u
     %span My Profile   
  %li
   = link_to "The IVF Process", {:controller => 'reports', :action => 'the_ivf_process'}
  -#%li 
   =# link_to "Infertility Diagnoses", {:controller => 'reports', :action => 'infertility_diagnoses'}
  %li
   = link_to "The CDC vs SART", {:controller => 'reports', :action => 'cdc_vs_sart'}
  %li
   = link_to "Fertility News", {:controller => 'reports', :action => 'fertility_news'}
  %li.bottom
   = link_to "Other Technologies", {:controller => 'reports', :action => 'other_technologies'}
  -#%li.bottom
   = #link_to "Clinics By State", {:controller => 'clinics', :action => 'index'}
 
 - if signed_in?
  - if current_user.admin? || current_user.insurer?
   %ul.sidebar_module
    %li.header Optum Health
    %li
     = link_to "Clinic Explorer", {:controller => 'reports', :action => 'clinic_explorer'}
    %li.bottom
     = link_to "Clinic Comparator", {:controller => 'reports', :action => 'clinic_comparator'} 	   	   

 %ul.sidebar_module
  %li.header Social Media
  %li.social_media
   .facebookbadge.small-round
    %iframe{ :src => "http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FIVF-Reports%2F166670843383510&amp;width=190&amp;colorscheme=light&amp;show_faces=false&amp;stream=false&amp;header=false&amp;height=62", :scrolling => "no", :frameborder => "0", :style => "border:none; width:190px; height:80px;", :allowTransparency => "true" }
  %li.social_media.bottom
   .twitterbadge.small-round
    %a{ :href => "http://www.twitter.com/ivfreports"}
     %img{ :src => "http://twitter-badges.s3.amazonaws.com/follow_us-b.png", :alt => "Follow ivfreports on Twitter"}     

app/views/layouts/_meta.html.erb
<meta name='description' content='IVF Reports empowers infertile couples by helping them find the best fertility clinic to treat their specific type of infertility. Fertility Clinics are evaluated according to historical performance, and the data help couples bring a happy, healthy child into this world.'>
<meta name='keywords' content='IVF Reports, Fertility, Infertility, IVF Clinic, IVF, Best IVF Clinics, Top IVF Clinics, Pregnancy, Embryos, Reproduction, Reproductive Medicine, Assisted Reproductive Technology, <% if is_controller?('clinics') && is_action?('show') %>
<%= "#{@clinic.clinic_name}, #{@clinic.practice_director}, #{@clinic.medical_director}, #{@clinic.laboratory_director}" %>
<% end %>'>
<meta name="google-site-verification" content="b4VS-QYAuuj2LQ_7n52YyXhZa4pbIqZiE60o7T2Qc0c" />
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20171924-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% if is_controller?('clinics') && is_action?('show') %>
	<meta name="geo.position" content="<%= "#{@clinic.latitude};#{@clinic.longitude}" %>">
	<meta name="ICBM" content="<%= "#{@clinic.latitude};#{@clinic.longitude}" %>">
	<meta name="geo.region" content="<%= "US-#{@clinic.state}" %>">
	<meta name="geo.country" content="US">
	<meta name="city" content="<%= @clinic.city %>">
	<meta name="state" content="<%= @clinic.state %>">
	<meta name="zipcode" content="<%= @clinic.zip %>">			
<% end %>

app/views/layouts/_region_map.html.haml
#us_region_map.region_map
 %h1 Select a Region
 #ESC.map_region
 #WSC.map_region
 #MT.map_region
 #SP.map_region
 #NE.map_region
 #SA.map_region
 #OTH.map_region
 #WNC.map_region
 #ENC.map_region
 #MA.map_region
 #NP.map_region

app/views/layouts/_right_sidebar.html.haml
.right_sidebar
 - if is_controller?('clinics') && is_action?('show')
  - unless signed_in? && (current_user.clinician? || current_user.admin?)	 
   %ul.sidebar_module
    %li.header Contact this Clinic
    - if signed_in?
     - if @clinic.requests.where(:user_id => current_user.id).count == 1
      %li.request_button.bottom
       %a{ :href => "#" }
        %span.request_bottom_old Contact Request Sent
     - else
      %li.request_button.bottom
       = form_for @request, :remote => :true do |f|
        = f.hidden_field :user_id, :value => current_user.id   
        = f.hidden_field :clinic_id, :value => @clinic.id
        = f.submit :value => 'Click Here to Contact'  	    
    -else
     %li.request_button.bottom
      = link_to 'Register to Contact', register_path    

 - if signed_in? && current_user.admin?
  - unless @clinic.nil?
   %ul.sidebar_module
    %li.header Manage Clinic Info
    %li
     = link_to 'Edit Clinic Info', edit_clinic_path(@clinic)
    %li
     = link_to 'View In Depth Statistics', clinic_statistics_path(@clinic)
    %li.bottom
     = link_to 'View Patient Leads', [@clinic, :requests]        
 
 - if signed_in? && current_user.clinician?
  - unless user_clinic.nil?
   %ul.sidebar_module
    %li.header Manage My Clinic Info
    %li 
     = link_to 'View My Clinic', clinic_path(user_clinic)
    %li 
     = link_to 'Edit Clinic Info', edit_clinic_path(user_clinic)
    %li 
     = link_to 'View In Depth Statistics', [user_clinic, :statistics]            
    %li.bottom
     = link_to 'View Patient Leads', [user_clinic, :requests]
 - else
  -# Nothing displayed
  
 - if is_controller?('pages') && is_action?('ranking')
  %ul.sidebar_module
   %li.header Select States
   %li

    -#need to set default checkbox values
    %span.all_state_label Select All States
    %input{ :type => "checkbox", :class => "select_all_state_checkbox", :name => "select_all_states", :value => "all_states", :style => "float:right;margin-top:9px;margin-right:10px;" }
   %li
    %span.all_state_label Unselect All States
    %input{ :type => "checkbox", :class => "unselect_all_state_checkbox", :name => "unselect_all_states", :value => "no_states", :style => "float:right;margin-top:9px;margin-right:10px;" }
   
   -# there is an issue with the code below because the original html had a nesting issue. it currently produces a single column of checkboxes, when there should be two columns

   - @states.each_with_index do |s, index|
    - if index%2 == 0
     %li.state
      %span.state_span
       %span
        = s.name  
       %input{ :class => "state_checkbox", :type => "checkbox", :name => "state", :value => "#{s.name}" }
    - else
     %li.state
      %span.state_span
       %span
        = s.name  
       %input{ :class => "state_checkbox", :type => "checkbox", :name => "state", :value => "#{s.name}" }
 
 %ul.sidebar_module
  %li.header Links
  %li
   = link_to "The CDC", 'http://www.cdc.gov/art/', :target => "_blank"
  %li
   = link_to "SART", 'http://www.sart.org/', :target => "_blank"
  %li
   = link_to "IVF.NET", 'http://www.ivf.net/', :target => "_blank"
  %li
   = link_to "ASRM", 'http://www.asrm.org/', :target => "_blank"
  %li
   = link_to "RBM Online", 'http://www.rbmojournal.com/', :target => "_blank"
  %li.bottom
   = link_to "American College of Embryology", 'http://embcol.org/', :target => "_blank"

 - if is_controller?('users') && is_action?('show')
  %ul.sidebar_module.tips_for_success
   %li.header Tips for Success
   %li.tip *Fill out as much information as possible to help the physicians who you contact gauge whether you are a good fit for their clinic. This also makes sure that our recommendation engine matches you with the best clinics for you.
   %li.tip *You may contact up to 5 clinics at a time. If contact is declined by a clinic, feel free to contact a new clinic. Again, the more information in your profile (Phone Number, Age, About Me, Zip Code), the higher the chances that a clinic will follow up with an appointment.
   %li.tip *Describe more details about your fertility issues in the 'About Me' section. Don't worry fields marked 'Clinic Contact Only' are not shared with anyone except for clinics you explicitly contact.
   %li.tip.bottom 
    %span
     = link_to 'Contact', contact_path
    %span an IVF Reports representative with any issues or questions. We want to help you navigate through this difficult time, and we have representatives ready to point you in the right direction.
     
        

app/views/layouts/application.html.haml
!!!XML
!!!

%html
 %head
  %title
   = title
  %span
   = stylesheet_link_tag    "application"
   = javascript_include_tag "application"
   = render 'layouts/meta' if Rails.env.production?
  %link{ :rel => "shortcut icon", :href => "#{asset_path 'favicon.png'}"}  
  %link{ :rel => "icon", :href => "#{asset_path 'favicon.png'}"}  
  %span
   = csrf_meta_tags

 %body
  .container
   %span
    = render 'layouts/header'
   %section.page-body-content
    .container_12
     .grid_12.body_content
      - if is_clinic_index?
       .middle_content
        = yield
      - elsif is_clinic_explorer? || is_clinic_comparator? || is_controller?('statistics')
       .explorer_content
        - flash.each do |key, value|  
         .grid_9.alpha
          %div{ :class => "flash #{key}"}
           = value
        %span
         = yield   
      - else 
       - if is_controller?('pages') && is_action?('ranking') 
        %span
         = render 'layouts/region_map'
        .hidden#ranking_content
         .grid_3.alpha
          = render 'layouts/left_sidebar'
         - if is_controller?('pages') && is_action?('home')
          - unless signed_in?
           .grid_9.omega
            = render 'layouts/call_to_action'
         .grid_6
          .middle_content
           - flash.each do |key, value|  
            .grid_6.alpha
             %div{ :class => "flash #{key}"}
              = value       
           %span
            = yield
         .grid_3.omega
          = render 'layouts/right_sidebar'
       - else
        .grid_3.alpha
         = render 'layouts/left_sidebar'
        - if is_controller?('pages') && is_action?('home')
         - unless signed_in?
          .grid_9.omega
           = render 'layouts/call_to_action'
        .grid_6
         .middle_content
          - flash.each do |key, value|  
           .grid_6.alpha
            %div{ :class => "flash #{key}"}
             = value       
          %span
           = yield
        .grid_3.omega
         = render 'layouts/right_sidebar'

   %span
    = render 'layouts/footer'
  %span
   = debug(params) if Rails.env.development?